/* -*- mode: c++; indent-tabs-mode: nil -*- */
/** @file treesitter-module.cpp tree-sitter module for Qore */
/*
    Qore Programming Language

    Copyright (C) 2026 Qore Technologies, s.r.o.

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

#include "treesitter-module.h"

#include <cstdarg>

// Forward declarations for class init functions (generated by qpp)
void preinitTreeSitterParserClass();
void preinitTreeSitterTreeClass();
void preinitTreeSitterNodeClass();
void preinitTreeSitterCursorClass();
void preinitTreeSitterQueryClass();
QoreClass* initTreeSitterParserClass(QoreNamespace& ns);
QoreClass* initTreeSitterTreeClass(QoreNamespace& ns);
QoreClass* initTreeSitterNodeClass(QoreNamespace& ns);
QoreClass* initTreeSitterCursorClass(QoreNamespace& ns);
QoreClass* initTreeSitterQueryClass(QoreNamespace& ns);

static void treesitter_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink);
static void treesitter_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink);
static void treesitter_module_delete();

extern "C" DLLEXPORT void treesitter_qore_module_desc(QoreModuleInfo& mod_info) {
    mod_info.name = "treesitter";
    mod_info.version = TREESITTER_MODULE_VERSION;
    mod_info.desc = "Tree-sitter parsing library bindings for Qore";
    mod_info.author = "Qore Technologies, s.r.o.";
    mod_info.url = "https://qore.org";
    mod_info.api_major = QORE_MODULE_API_MAJOR;
    mod_info.api_minor = QORE_MODULE_API_MINOR;
    mod_info.init = treesitter_module_init;
    mod_info.ns_init = treesitter_module_ns_init;
    mod_info.del = treesitter_module_delete;
    mod_info.license = QL_MIT;
    mod_info.license_str = "MIT";
}

// Module namespace
QoreNamespace TreeSitterNS("TreeSitter");

void raiseTreeSitterException(ExceptionSink* xsink, const char* err, const char* fmt, ...) {
    QoreStringNode* desc = new QoreStringNode();
    va_list args;
    va_start(args, fmt);
    desc->vsprintf(fmt, args);
    va_end(args);
    xsink->raiseException(err, desc);
}

static void treesitter_module_init(QoreModuleInitContext& ctx, ExceptionSink& xsink) {
    // Initialize the language registry
    TreeSitterLanguages::isLanguageSupported("python");  // Triggers init without allocation

    // Pre-initialize class stubs to handle circular dependencies
    preinitTreeSitterParserClass();
    preinitTreeSitterTreeClass();
    preinitTreeSitterNodeClass();
    preinitTreeSitterCursorClass();
    preinitTreeSitterQueryClass();

    // Now fully initialize the classes and add to namespace
    TreeSitterNS.addSystemClass(initTreeSitterParserClass(TreeSitterNS));
    TreeSitterNS.addSystemClass(initTreeSitterTreeClass(TreeSitterNS));
    TreeSitterNS.addSystemClass(initTreeSitterNodeClass(TreeSitterNS));
    TreeSitterNS.addSystemClass(initTreeSitterCursorClass(TreeSitterNS));
    TreeSitterNS.addSystemClass(initTreeSitterQueryClass(TreeSitterNS));

    // Add constants for language names
    TreeSitterNS.addConstant("LANG_PYTHON", new QoreStringNode("python"));
    TreeSitterNS.addConstant("LANG_JAVA", new QoreStringNode("java"));
    TreeSitterNS.addConstant("LANG_JSON", new QoreStringNode("json"));
    TreeSitterNS.addConstant("LANG_YAML", new QoreStringNode("yaml"));
    TreeSitterNS.addConstant("LANG_JAVASCRIPT", new QoreStringNode("javascript"));
    TreeSitterNS.addConstant("LANG_KOTLIN", new QoreStringNode("kotlin"));

}

static void treesitter_module_ns_init(QoreNamespace* rns, QoreNamespace* qns, ExceptionSink& xsink) {
    rns->addNamespace(TreeSitterNS.copy());
}

static void treesitter_module_delete() {
    // Cleanup if needed
}
